import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>TeamTS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-100 flex items-center  justify-center">
        <Link href="/typing">
          <div className="rounded-pill w-[170px] bg-blue-500 px-4 py-2 font-bold text-white">
            Go to typing test, TODO: turn this into auth page
          </div>
        </Link>
      </div>
    </>
  );
}
