import Head from "next/head";
import Link from "next/link";
import { useSession, signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
export default function Home() {
  const { data: session } = useSession();
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { push } = useRouter();

  useEffect(() => {
    if (session) {
      push("/typing");
    }
  }, [push, session]);
  return (
    <>
      <Head>
        <title>TeamTS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="align-center flex h-[100vh] flex-col items-center justify-center">
        {session ? (
          <Link href="/typing">
            <div className="rounded-pill w-[170px] bg-blue-500 px-4 py-2 font-bold text-white">
              Go to typing test
            </div>
          </Link>
        ) : (
          <button
            // eslint-disable-next-line @typescript-eslint/no-misused-promises
            onClick={() => signIn()}
            className="rounded-pill w-[170px] bg-blue-500 px-4 py-2 font-bold text-white"
          >
            Sign in
          </button>
        )}
      </div>
    </>
  );
}
